---
# tasks file for web
- name: Ensure need package for web is present
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - default-jre
    - tomcat9

- name: Ensure hello-1.0.war is present
  copy:
    src: "{{ src_path }}/hello-1.0.war"
    dest: "{{ dest_folder }}"
  delegate_to: 35.232.153.81
  notify:
    - restart tomcat9
    