---
# tasks file for web
- name: Ensure need package for web is present
  apt:
    name: {{item}}
    state: present
  with_items:
    - default-jre
    - tomcat9
- name: Ensure tomcat started
    apt:
      name: tomcat9
      state: started
    